name: Chariot Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        cd src
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        flake8 chariot
#     - name: Lint with pylint
#       run: |
#         pip install pylint
#         pylint chariot
#     - name: Typecheck with mypy
#       run: |
#         pip install mypy
#         mypy chariot
    - name: Security scan with bandit
      run: |
        bandit -r chariot
    - name: Test with pytest
      run: |
        pytest -v test
